#!/bin/sh
#
# web2rgbmatrix Daemon Script
#

. /media/fat/web2rgbmatrix/web2rgbmatrix-system.ini
. /media/fat/web2rgbmatrix/web2rgbmatrix-user.ini

# Start
start() {
    if [[ -x ${DAEMONSCRIPT} ]]; then
      echo "Starting ${DAEMONNAME}..."
      ${DAEMONSCRIPT} &
    else
      echo "${DAEMONSCRIPT} not found!"
    fi
}

# Stop
stop() {
    echo "Stopping ${DAEMONNAME}..."
    killall ${DAEMONNAME}
}

case "$1" in
  start)
        start
        ;;
  stop) 
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
